name: Java CI with Maven - Test and package

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Étape pour mettre en cache les dépendances Maven
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository  # Dossier de cache Maven local
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}  # Clé de cache basée sur le hash de pom.xml
          restore-keys: |
            ${{ runner.os }}-maven-  # Clé de secours en cas de cache partiel

      # Étape pour mettre en cache les dépendances SonarQube
      - name: Cache SonarQube packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache  # Chemin où SonarQube stocke ses packages
          key: ${{ runner.os }}-sonarqube-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-sonarqube-

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Build and Analyze with SonarQube
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey=$(echo ${{ github.repository }} | sed 's-/-_-') \
            -Dsonar.login=$SONAR_TOKEN
