name: Documentation

on:
  pull_request:
    types:
      - closed  # Le pipeline se déclenche lorsque la pull request est fermée

jobs:
  deploy-documentation:
    if: github.event.pull_request.merged == true  # Vérifie que la PR a été fusionnée

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: Generate Javadoc
        run: mvn -B javadoc:javadoc  # Génère la documentation Java avec Maven

      - name: Deploy documentation to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Utilise le jeton GitHub pour l'authentification
          publish_dir: ./target/site/apidocs  # Répertoire généré contenant la documentation
          publish_branch: gh-pages  # Crée la branche gh-pages si elle n'existe pas
